app_module_notebook.ui.notebook.list:
    path:     /
    defaults: { _controller: AppModuleNotebookModuleNotebookUiBundle:Notebook:index }

app_module_notebook.ui.notebook.view:
    path:     /{slug}/view
    defaults: { _controller: AppModuleNotebookModuleNotebookUiBundle:Notebook:view }

app_module_notebook.ui.notebook.create:
    path:     /create
    defaults: { _controller: AppModuleNotebookModuleNotebookUiBundle:Notebook:create }

app_module_notebook.ui.notebook.update:
    path:     /{slug}/edit
    defaults: { _controller: AppModuleNotebookModuleNotebookUiBundle:Notebook:update }

app_module_notebook.ui.notebook.delete:
    path:     /{slug}/delete
    defaults: { _controller: AppModuleNotebookModuleNotebookUiBundle:Notebook:delete }
